### ISSUE TITLE
[Feature Request] Add OpenSubtitles

### ISSUE THREAD

**Issue by as280093** [HandyOrg/HandySub#87]
OpenSubtitles.org has api i think which provides language based subtitles 
https://github.com/emericg/OpenSubtitlesDownload/

**Comment by ghost1372** [comment]
excellent I will add OpenSubtitles soon Thanks for the suggestion

**Comment by ghost1372** [comment]
OpenSubtitles API seems to have a lot of limitations So I have to parse HTML pages

**Comment by as280093** [comment]
that might cause IP Ban 
but allowing login 
as if the parse is doing while login it will auto-filter other language which was set in Opensubtitles settings

**Comment by ghost1372** [comment]
Hi @as280093 API is not very important I can do this without API, but unfortunately they have a lot of restrictions on their website. I can not add Opensubtitles to the HandySub because They have limited everything to the VIP user
- The user has to wait 20 seconds to download the subtitle
- The number of subtitle downloads per day is limited

Whenever they remove their restrictions, I quickly add Opensubtitles to HandySub
